### ISSUE TITLE
Understanding Verification Better

### ISSUE THREAD

**Issue by skilesare** [Brightside-Social/brightside#1]
Perhaps I'm not understanding, but doesn't the fact that one can create sybils with enough colluders mean that there will be sybils?  And if there are sybils doesn't that limit the usefulness of the system?

> For example, with 4 verifications needed per recruit and 300 colluding attackers, 99 sybils could be verified initially and 149 total if the new sybils are reused for verification.

It would seem that if 300 attackers could create 149 accounts this would be very attractive to do in Basic Income scheme.  If the Basic income is $100 a month, now these 300 are getting ~$150.

Perhaps there is some sort of revolving re-verification that is involved?  Or some kind of staking that needs to happen?

**Comment by adamstallard** [comment]
You're understanding it correctly, although the mathematical details of that section need updating.  There will be sybils, and sybils do limit the usefulness of the system--for some applications more than others.

There are two ways to improve the situation 1. convince the app developers that the number of sybils that will exist isn't a show-stopper 2. put more protections in place.  These often work together.

I'm interested in adding any protections that will put app developers' minds at ease, even if they're just "feel good" solutions with no provable guarantees.  If you think about it, in our current voting and welfare systems, how many fraud protection measures come with a guarantee?  We like the idea of secret ballots to prevent vote-buying, but where's the proof of effectiveness beyond just feeling good about it?

Would revolving re-verification improve things?  Couldn't a group of attackers just reverify their sybils using a different combination of attackers from their group for each round?  If not, then isn't this something we can prevent just as well in the initial verification--using anti-combining rules, for instance?

Staking is an interesting idea.  Could you elaborate on how that might work?

I've also thought of allowing app devs to include their own additional verification awards--for instance, you could have the basic "social graph" verification award, and maybe for a certain voting app, that's deemed sufficient, but the BI app wants more, so they have additional steps users take to achieve verification awards such as "synchronized video chat" or "photo Id" or "unique geolocation" or "utility bill", which are awarded by the BI app (but can be reused by other apps, if desired).  These verification awards could also have an expiration date.

Let's try to look intuitively at the social graph verification system.  We can only guess at how many people will try to become attackers.  Maybe my intuition tells me that only 1 in 200 people will try to attack the system, and only 1 in 1000 will be successful at finding enough colluders, and 99% of those will only have a group of colluders that is barely sufficient, meaning they will only have ``1/v`` sybils each.  That means in a system with 1 million users, there will only be ~100 sybils.  But this isn't a guarantee, it's only an intuition.

Think of alternative solutions, such as Id cards, video proofs, biometrics, etc.  They lack any sort of provable guarantee.  We only have our intuition to tell us they're effective at limiting fraud.  That doesn't mean we should discount our intuition; certainly not.

There's also a trade-off here in that every measure we use to prevent sybils also makes it more difficult for a real, honest user to be verified, and making the process too strict could harm the system as much or more as the presence of sybils.

These are the protections against sybils we currently have, some of which may be clear, and some of which need to be more explicitly stated in the documentation:

1. You must be verified in the system, meaning you must find ``v`` verified users willing to vouch that you're a real, well-behaving person.  They can choose to revoke their verification.  ``v`` is the number of verifiers needed to verify a recruit.  This number grows as the overall number of verified users grows.
1. You must find ``v - 1`` other attackers to collude with you.  
1. If you attempt to collude with someone, they could alert others of your behavior, who could revoke their verification of you.  Others might be less likely to re-verify you.
1. There is a non-combining rule.  This says that for ``k * 2`` hops, going from recruits to verifiers to recruits to verifiers, etc. any combination of verifiers encountered can't be used again to verify a future recruit.  With ``k = 1``, that means no verifier can work with another verifier more than once.  For ``k > 1``, this restriction becomes greater, looking at "ancestor" verifiers, so to speak.  For practical purposes, ``k`` will be 2 or 3.

In the beginning, there will be little incentive to make sybils, because the payout will be low or non-existent.  As the number of verified users grows, the verification requirements should become stricter.  With the current idea, that means the variable ``v`` would increase as the number of currently verified users increases.

Something that may be frustrating is there's no way to know how many sybils there are.  We can only know an upper bound, and lowering that upper bound is difficult.  It's also going to be phrased in terms of the number of colluding attackers in a group, which is unknown.  If everyone decides to become an attacker, there's no limit, and we're in trouble.  Measures can be introduced that might actually reduce the number of sybils, but still not improve the guarantee.

**Comment by adamstallard** [comment]
Please look at the [updated security documentation](https://github.com/adamstallard/brightside/blob/master/security.md).

Our goal should be to allow for every possible measure to protect against sybils.

You'll notice I've removed any reference to the "non-combining rule".  That's because it's an advanced feature that may not be needed.  Simple verification and sybilInfer might be enough.

**Comment by adamstallard** [comment]
We are moving away from the notion of a binary "verified" status to providing apps with a user's uniqueness score and the number and uniqueness scores of their contacts.  The app then sets its own thresholds for unlocking user privileges based on this data.
